# Generated by Django 5.2.7 on 2025-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('capital', models.CharField(max_length=256, null=True)),
                ('region', models.CharField(max_length=256, null=True)),
                ('population', models.IntegerField(default=0)),
                ('currency_code', models.CharField(max_length=5, null=True)),
                ('exchange_rate', models.FloatField(null=True)),
                ('estimated_gdp', models.FloatField(default=0, null=True)),
                ('flag_url', models.CharField(max_length=512, null=True)),
                ('last_refreshed_at', models.DateTimeField()),
            ],
        ),
    ]
